Used open graph protocol to add site meta data
nullNEU/nullify pull request #53
Opened 2024-11-23 10:39 UTC by SirChronicle

parameters used:

title: "Null NEU"
description: "A cybersecurity club at Northeastern University focused on learning and sharing knowledge in security."

2024-11-26 20:57 UTC, Parthiv-M requested changes
The approach is spot on, just some more improvements!

- Would be helpful if we can add the following tags

  ```
  <meta name="description" content="{{ if .Description }}{{ .Description }}{{ else }}{{ .Site.Params.description }}{{ end }}" />
  
  <meta name="twitter:title" content="{{ .Title }} | {{ .Site.Title }}" />
  <meta name="twitter:image" content="{{ .Site.Params.og_image | absURL }}" />
  
  <meta itemprop="name" content="{{ .Title }} | {{ .Site.Title }}" />
  <meta name="application-name" content="{{ .Title }} | {{ .Site.Title }}" />
  
  <meta property="og:title" content="{{ .Title }} | {{ .Site.Title }}" />
  <meta property="og:type" content="website" />
  <meta property="og:title" content="{{ .Site.Title }}" />
  <meta property="og:description"content="{{ if .Description }}{{ .Description }}{{ else }}{{ .Site.Params.description }}{{ end }}" />
  <meta property="og:site_name" content="{{ .Site.Title }}" />
  <meta property="og:url" content="{{ .Permalink }}" />
  <meta property="og:locale" content="en">
  <meta property="og:image" content="{{ .Params.Site.BaseURL }}{{ .Site.Params.og_image | relURL }}" />
  <meta property="og:image:secure_url" content="{{ .Site.Params.og_image | absURL }}" />
  <meta property="og:type" content="website" />
  ```

This is just something I got off another resource, please validate and modify accordingly before including in our partial.

2024-11-26 20:57 UTC, Parthiv-M commented on layouts/partials/opengraph.html
> +{{ end }}
Can be simplified to `<meta property="og:title" content="{{ .Site.Params.title }}" />`

2024-11-26 20:57 UTC, Parthiv-M commented on layouts/partials/opengraph.html
> +{{ end }}
Same as above

2024-11-28 12:11 UTC, SirChronicle commented
I've added the suggested meta tags after reviewing each (commented all tags for images for future updates) and updated the relevant files. Let me know if there's anything else to adjust!

2024-11-30 04:24 UTC, merged